/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBatchesRouteImport } from './routes/admin.batches'
import { Route as AdminAppealsRouteImport } from './routes/admin.appeals'
import { Route as AdminTransactionFailedRefRouteImport } from './routes/admin.transaction-failed.$ref'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppealsRoute = AdminAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionFailedRefRoute =
  AdminTransactionFailedRefRouteImport.update({
    id: '/transaction-failed/$ref',
    path: '/transaction-failed/$ref',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/wizard': typeof WizardRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/admin/transaction-failed/$ref': typeof AdminTransactionFailedRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/wizard': typeof WizardRoute
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/admin/transaction-failed/$ref': typeof AdminTransactionFailedRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/wizard': typeof WizardRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/admin/transaction-failed/$ref': typeof AdminTransactionFailedRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/wizard'
    | '/worker'
    | '/admin/appeals'
    | '/admin/batches'
    | '/admin/dashboard'
    | '/admin/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/'
    | '/worker/'
    | '/admin/transaction-failed/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/wizard'
    | '/admin/appeals'
    | '/admin/batches'
    | '/admin/dashboard'
    | '/admin/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/admin'
    | '/worker'
    | '/admin/transaction-failed/$ref'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/dashboard'
    | '/wizard'
    | '/worker'
    | '/admin/appeals'
    | '/admin/batches'
    | '/admin/dashboard'
    | '/admin/wallet'
    | '/auth/login'
    | '/auth/signup'
    | '/admin/'
    | '/worker/'
    | '/admin/transaction-failed/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  WizardRoute: typeof WizardRoute
  WorkerRoute: typeof WorkerRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appeals': {
      id: '/admin/appeals'
      path: '/appeals'
      fullPath: '/admin/appeals'
      preLoaderRoute: typeof AdminAppealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transaction-failed/$ref': {
      id: '/admin/transaction-failed/$ref'
      path: '/transaction-failed/$ref'
      fullPath: '/admin/transaction-failed/$ref'
      preLoaderRoute: typeof AdminTransactionFailedRefRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppealsRoute: typeof AdminAppealsRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTransactionFailedRefRoute: typeof AdminTransactionFailedRefRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppealsRoute: AdminAppealsRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTransactionFailedRefRoute: AdminTransactionFailedRefRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WorkerRouteChildren {
  WorkerIndexRoute: typeof WorkerIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerIndexRoute: WorkerIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  WizardRoute: WizardRoute,
  WorkerRoute: WorkerRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
